### ISSUE TITLE
Paul zobs

### ISSUE THREAD

**Issue by paulzobs** [paulzobs/components-on-a-grid#1]
bulk0002@algonquinlive.com

**Comment by MacKenzieRose** [comment]
Hey~

Just so you know, to tag me on Github in Issues, you'll need to write `@mackenzierose` for me to get a notification.

I'll look at your code now :)

**Comment by MacKenzieRose** [comment]
Okay so you have a super good start! 

For grid-areas, the first thing we need to set up is a `grid-template-area` on the container/parent element for our grid. This is how the layout is build, as a 2x2 grid:

<img width="715" alt="image" src="https://user-images.githubusercontent.com/19557909/93814291-539b5d80-fc22-11ea-9652-29d28de752d9.png">


Coding-wise, this means you'll add a grid-template-area to your body tag in the CSS, and then assign each area name to the right elements.

Does that help you get started?

**Comment by paulzobs** [comment]
yea that's kinda what I was thinking, but I was struggling with the naming of grid-template-area, I thought I could do something like body { grid-template-area: "main main" "figure figure" } I know the first line will be main main, but cant figure out how to decipher the two figures to make the second row 
@mackenzierose

**Comment by MacKenzieRose** [comment]
For the `grid-template-areas` you can name them anything! However, make sure that different areas have different names ex. `grid-template-areas: "billy billy" "bob jeff"` . (If you can, also pick meaningful names for areas, to help you remember what they're for!)

The starter code you were given gave `display: contents` to the header tag, which means that you can target the `figure` tags directly...maybe with figure:nth-of-type(x) ? 😸

**Comment by paulzobs** [comment]
awesome, thank you!!
