### ISSUE TITLE
grid-template-area

### ISSUE THREAD

**Issue by paulzobs** [paulzobs/components-on-a-grid#2]
Ive been going around in circles a bit cant figure out what I'm missing, Im pretty sure this is the basic set up.
@mackenzierose

**Comment by paulzobs** [comment]
Yea, if you have would you mind sending me your code? We can't submit it anymore, just to see what Im missing.

**Comment by MacKenzieRose** [comment]
Academic integrity-wise, I can't send you my stuff 😞 

However, all of the repositories we use for school assignments are public, so if you look through the assignment forks ([link here](https://github.com/acgd-webdesign-2/components-on-a-grid/network/members)), you might find what you're looking for. 🙂

**Comment by paulzobs** [comment]
I totally understand. No way thats wild, thank you!
